# Generated by Django 5.2.14 on 2026-05-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
