# Generated by Django 5.2.14 on 2026-05-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
