# Generated by Django 5.2.14 on 2026-05-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_alter_contact_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('processing', 'В обработке'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
